[package]
name = "engine-integration-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
alloy = { workspace = true, features = ["serde", "signer-local", "eip712"] }
tokio = { workspace = true, features = ["full"] }
serde_json = { workspace = true }
engine-core = { path = "../core" }
engine-aa-types = { path = "../aa-types" }
thirdweb-core = { path = "../thirdweb-core" }
